"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < CreateCollections.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < AirportWithCargo.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < Airport.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < ServiceArea.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < AirportServiceArea.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < TravelCost.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < TravelMode.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < AirportTime.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < EquipmentModel.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < AirportEquipment.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < Equipment.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < EquipmentPM.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < EquipmentCM.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < CMRate.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < LaborRule.json
"\Program Files\MongoDB\Server\4.4\bin\mongo.exe" < TravelRule.json
